### ISSUE TITLE
op_ver support and documentation

### ISSUE THREAD

**Issue by lutzroeder** [OAID/Tengine#365]
@BUG1989 @pierricklee @LEMON-LM can you clarify the semantics for `op_ver` in `TM2_Operator` and provide fixes for tools as you make breaking changes to the format.

For example, [retinaface_benchmark.tmfile](https://github.com/OAID/Tengine/blob/tengine-lite/benchmark/models/retinaface_benchmark.tmfile) fails to render (see below). Why did `op_ver` change for all operators while the `struct` format for most operators did not change? Isn't the goal of `op_ver` to version changes for each operator individually so the version for an operator only needs to change if the operator data structure changes?

See also #261.

<img width="1136" alt="screenshot" src="https://user-images.githubusercontent.com/438516/89480547-7cd35d80-d74a-11ea-9d81-5af9c2dbaafb.png">

**Comment by li-zihang** [comment]
Hi Lutz,

Thanks for supporting Tengine!

That is a bug. We tried to fix the issue you mentioned in #261 , but it left a bug within the convert tool. It was because we tried to make Tengine itself be compatible with previous tmfiles. These old copies of tmfile models do not have any flags to be distinguished from new tmfiles which have different operator format. In another word, Tengine's old Model Zoo were released but `op_ver` wasn't used, it all remains default `1` for all previous tmfiles.

That's a mistake, our solution seems work not very well and even makes Netron crash down. 

The new idea is:
1. `Convert Tool` will be independent from Tengine as a repo individually, now it also has a [online version](https://convertmodel.com/);
2. New Model Zoo will be maintained by new `Convert Tool` throughtly;
3. `tmfile` is now in it's version 2, it will be updated to V3 for more compatibility;
4. Old tmfile copies will not be supported by latest `Tengine` or `Tengine-Lite`, we recommend users to get new tmfiles from Model Zoo, or convert models with new 'Convert Tool' by themselves.

I will request PR for these changes (to Netron) as long as they are ready.

Regards,

Pierrick
